### ISSUE TITLE
issue installing focal repos for minknow

### ISSUE THREAD

**Issue by vmkhot** [sirselim/jetson_nanopore_sequencing#14]
Hi Miles,

I'm following your tutorial on installing MinKnow and GPU guppy on Ubuntu 20.04. I'm having difficulty with installing the Focal repo. There are no errors as such, it just doesn't install anything. My feeling is that it's an issue with the repos being saved to stdout for some reason. Below is a screenshot of what I'm seeing on my terminal. Any help is much appreciated! 

![Screenshot from 2021-09-19 11-47-00](https://user-images.githubusercontent.com/50498740/133937564-ff71f81c-6e4f-454e-9f68-ce09d45e7aef.png)

Thanks,

Varada

**Comment by sirselim** [comment]
Hi @vmkhot - from the above I'm not too sure what the problem is. The Focal repo appears to have been added correctly, you just haven't run an `apt update` to refresh the available packages. If you don't have any ONT packages installed then `apt list --installed` and `apt list --upgradable` are not going to have anything to report back.

I do see an "issue" however, and that's that you still have the bionic repo active. You can see it listed in the output of the `apt update` at the top of the screenshot. Unless you are absolutely sure of what you are doing this is not recommended. I would run a `sudo apt update` and then see if adding the Focal repo has replaced this. If it hasn't then you'll need to manually correct the issue. This can be don by commenting out the bionic repo in the apt list file, you want it to look like below:

```sh
$ cat /etc/apt/sources.list.d/nanoporetech.sources.list
# deb http://mirror.oxfordnanoportal.com/apt bionic-stable non-free
deb http://mirror.oxfordnanoportal.com/apt focal-stable non-free
```

Notice the '#' in front of the bionic line, that will no longer be read by apt. You can delete that line completely if Focal is working well, I just keep mine around for testing purposes. You need to use sudo to edit the above file, so as always take care.

**Comment by vmkhot** [comment]
Thanks for the reply!

`sudo apt update` seems to have fixed the issue. the bionic version was replaced by Focal. I'm able to proceed with the next steps :)
