### ISSUE TITLE
Not working with latest MinKNOW and switch to dorado_basecall_server

### ISSUE THREAD

**Issue by MatDaw** [sirselim/jetson_nanopore_sequencing#30]
Hello,

Just wanted to state that with latest versions of MinKNOW and switch from guppy to dorado basecall server any newer jetson device not based on CUDA 10 will not work for live basecalling. [This is response](https://github.com/nanoporetech/dorado/issues/772#issuecomment-2085369548) from Joyjit Daw form ONT regarding this issue.

I contacted ONT support to ask about the possibility of downloading an earlier version of MinKNOW but unfortunately since devices such as Jeston AGX Orin is not supported they do not provide such a possibility.

If someone has any idea how to overcome that I would be greatful for any help.

This is the error I'm getting:
```[ont/warning] dorado logger: Caught Torch error 'CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.', clearing CUDA cache and retrying.
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.```

**Comment by sirselim** [comment]
Hi @MatDaw - yes this is well established. At this point there is no support for ARM outside of the TX2 board that is in the Mk1C unit. Due to the dorado-basecall-server for ARM being compiled against an older version of CUDA means that boards like the ORIN cannot run that piece of software.

As others have pointed out in that thread, the dorado basecaller is compatible and works well. So basecalling can be run after sequencing, or as in the tool NanoDip in a batched based approach based on the output of pod5 files.

In terms of that later example, I just noticed that the EPI2ME workflow `wf-basecalling' has a real-time option: https://github.com/epi2me-labs/wf-basecalling?tab=readme-ov-file#real-time-analysis-options
It might be possible to run this via nextflow and have it monitor an output directory and basecall in real time during sequencing. I haven't tested this at all, but it might be worth looking into.
