### ISSUE TITLE
Would be good to mention the "guppyd" service

### ISSUE THREAD

**Issue by jean-baka** [sirselim/jetson_nanopore_sequencing#8]
Hi Miles! Excellent notes, as usual! I have been fighting with the guppyd basecall server that was still running in the background, hence the guppy_basecall_server it was running was constantly respawning. That's something different from the "minknow" service, and it gave me trouble to enforce my new configuration settings for guppy (with GPU) because it kept on maintaining a guppy (CPU only) basecalling server up and running!

![guppyd service](https://user-images.githubusercontent.com/8513150/124615639-23097500-de7e-11eb-8a22-efb1c3918ccd.png)

**Comment by jean-baka** [comment]
This pertains to the live_basecalling.md page, around the section "wipe out all the currently running basecalling servers".

**Comment by sirselim** [comment]
Hi Jean-Baka! Thanks for the suggestion, I'll make that explicit in the notes. 

My recommendation in the forum posts has been to purge anything installed a part of the minion-nc meta-package, which includes ont-guppyd, but I'll make sure the notes reflect this.

**Comment by sirselim** [comment]
@jean-baka - so it turns out that the `ont-guppyd-for-minion` (or the various others, i.e. `ont-guppyd-for-minit`) is a very recent addition to the repositories (I think with this latest release). 

I'm a little concerned that they're moving towards needing another systemd service running in the background. BUT I've done some testing on both AMD64 and ARM systems and you don't actually need to have it installed. So as long as you stay away from the meta-package `minion-nc` it shouldn't be an issue - `guppy_basecall_server` seems to get started just fine by the `minknow.service` when it's up and running (which makes me wonder why ONT thinks guppy needs a background service as well...).

So I need to edit my notes to:

* make it clear that this is only a potential issue on AMD64/x86_x64 machines, not the ARM based Jetsons
* show how to check for the running service and kill it, and/or suggest purging all ONT packages before installing the latest software
  * continue to avoid `minion-nc` and proceed with a manual approach (using guppy downloaded from Community forum)

**Comment by jean-baka** [comment]
Yes @sirselim, that's actually how I got out of the woods: after installing the whole `minion-nc` (which, as you said, is no longer the recommended route), I _removed_ `ont-guppyd-for-minion` and `ont-guppy-cpu-for-minion`, and then was no longer annoyed by this guppyd systemd service.

And: yes, you're right, at the moment I'm using these notes on an x86_64 machine, not on an ARM-based architecture. Many thanks to you.

**Comment by sirselim** [comment]
Closing this issue now as I have updated with information on the `guppyd.service`.
