### ISSUE TITLE
Detailed example of what is needed to install guppy on ubuntu 20.04

### ISSUE THREAD

**Issue by namra1** [sirselim/jetson_nanopore_sequencing#9]
I really appreciate your detailed description to getting minknow software install on ubuntu 20.04. I had to do the following to install guppy with the latest version of minknow software : 
After following your instructions for installing non-guppy software packages : 
sudo apt install minknow-core-minion-nc ont-bream4-minion ont-configuration-customer-minion ont-kingfisher-ui-minion ont-vbz-hdf-plugin

I download ont_guppy_cpu_5.0.11-1~focal_amd64.deb from nanoporetech community website.
I had to manually install the following software packages:
sudo apt-get install libboost-atomic1.71.0,libboost-atomic1.71.0
sudo apt-get install libboost-atomic1.71.0
sudo apt-get install libboost-chrono1.71.0
sudo apt-get install libboost-program-options1.71.0
sudo apt-get install libboost-regex1.71.0 
sudo apt-get install libboost-system1.71.0
sudo apt-get install libboost-log1.71.0

before I could install the downloaded guppy  package.

sudo dpkg -i ont_guppy_cpu_5.0.11-1~focal_amd64.deb 

It would be nice to add above detail as an example for one route to getting minknow software on ubuntu 20.04.

**Comment by sirselim** [comment]
@namra1 - thanks for the feedback and suggestion, I'm glad things are working for you now. 

A couple of thoughts from my perspective:

* I don't recommend installing the `.deb` version of Guppy, which is why I refer to the pre-built binary version that is packaged (tarball) in any notes/documentation I write. This version can be downloaded and extracted and just works, it doesn't need any installation procedures. This is more user friendly, but more importantly means that multiple guppy versions can be maintained on the same system at the same time (see [here](https://github.com/sirselim/jetson_nanopore_sequencing/blob/main/live_basecalling.md#additional-guppy-versions) for examples). In theory it should mean that users don't have to worry about dependencies as much as the software is already built, but that may change.
* I'm not 100% sure why you had to install those boost libraries and don't want to 'recommend' people do that unless completely necessary (boost is not 'fun' to play with at the best of times). I've just checked several systems that I have running Focal (20.04) and they all have boost version 1.71.0 installed, even the fresh Pop!_OS 20.04 install on a laptop.  

So while it's likely completely safe to install all those libraries I don't recommend it unless the other options don't work. I may add a note as an aside, I just don't like confusing people with too many options and like to try and take the most 'simple' path to achieve the end result.

Can I ask a couple of questions:
* why did you decide to go with the `.deb` package over the pre-built version?
* was your system a fresh install of Ubuntu 20.04, or an upgrade from 18.04 or similar?

**Comment by sirselim** [comment]
@namra1 - I've just noticed that you mentioned you downloaded the CPU version of guppy (`ont_guppy_cpu_5.0.11-1~focal_amd64.deb`), is this a typo?

If you want to run CPU guppy you don't need to follow my guide, just install the `minknow-nc` package and resolve any boost dependencies like you have done. My set up guide/notes is for getting GPU live basecalling working.

**Comment by namra1** [comment]
Yes nstalled fresh Ubuntu desktop 20.04 and then guppy cpu not  gpu. 

I could not install cpu version via minknow-nc but had to  install as described.

Cheers,
Nasir

**Comment by sirselim** [comment]
I'm going to close this issue for now as it's quite edge case and I don't want to confuse people that are likely wanting to get set up for GPU basecalling. Plus, adding to that, the GPU version of Guppy is also a CPU caller, so doing the single set up is probably a more complete process.

**Comment by namra1** [comment]
Ok. I did not realize that you version also works with cpu only systems.

**Comment by sirselim** [comment]
Yes, with the GPU enabled version of Guppy of you don't use the `-X` or `--device` option then it will use your CPU for calling instead.
